### ISSUE TITLE
ERROR at //build/toolchain/concurrent_links.gni:90:19: Script returned non-zero exit code.

### ISSUE THREAD

**Issue by justkamiii** [ungoogled-software/ungoogled-chromium-windows#105]
I was trying to build ungoogled-chromium by following all of the steps shown in the README, but somehow, when I execute the build.py script, at some point it gives me this error after executing certain command:
```D:\ungoogled-chromium-windows\build\src>"out\Default\gn.exe" "gen" "out\Default" "--fail-on-unused-args"
ERROR at //build/toolchain/concurrent_links.gni:90:19: Script returned non-zero exit code.
  _command_dict = exec_script("get_concurrent_links.py", _args, "scope")
                  ^----------
Current dir: D:/ungoogled-chromium-windows/build/src/out/Default/
Command: C:/Users/Matias/AppData/Local/Microsoft/WindowsApps/python3.exe D:/ungoogled-chromium-windows/build/src/build/toolchain/get_concurrent_links.py --mem_per_link_gb=6
Returned 9009.
See //build/gn_logs.gni:5:1: whence it was imported.
import("//build/toolchain/concurrent_links.gni")
^----------------------------------------------
See //BUILD.gn:17:1: whence it was imported.
import("//build/gn_logs.gni")
^---------------------------

D:\ungoogled-chromium-windows\build\src>exit
Traceback (most recent call last):
  File "D:\ungoogled-chromium-windows\build.py", line 220, in <module>
    main()
  File "D:\ungoogled-chromium-windows\build.py", line 212, in main
    _run_build_process('out\\Default\\gn.exe', 'gen', 'out\\Default', '--fail-on-unused-args')
  File "D:\ungoogled-chromium-windows\build.py", line 64, in _run_build_process
    subprocess.run(('cmd.exe', '/k'),
  File "C:\Users\Matias\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('cmd.exe', '/k')' returned non-zero exit status 1.

D:\ungoogled-chromium-windows>```

Any ideas on any possible fix for this? Appreciated

**Comment by farteryhr** [comment]
> You probably need to restart CMD after turning off the python aliases. BTW, only Python 3.6 - 3.9 is supported.

> https://stackoverflow.com/questions/57485491/python-python3-executes-in-command-prompt-but-does-not-run-correctly
> 
> gn looks for Python 3 on Windows by default, and `python3` links to a wrapper that connects you to Microsoft Store.
> 
> ```gn
> # The python interpreter to use by default. On Windows, this will look
> # for python3.exe and python3.bat.
> script_executable = "python3"
> ```

fell into the very same pitfall here, plus using python 310.

please consider updating the "Building" section in README.md about it assuming `python3` command (which is not done by official python installer by default, and also windows 10 does this :shit: by default) and the minor version requirement.

and yes, the `domsubcache.tar.gz` pitfall got me too. please consider updating to "remove everything under `build\` other than `build\downloads_cache`".

thanks to this discussion, i only had to delete `build\[anything but src]` twice.
