### ISSUE TITLE
compile fail

### ISSUE THREAD

**Issue by galaxy4627** [ungoogled-software/ungoogled-chromium-windows#136]
`INFO: Path has no substitutions: chrome/browser/ash/child_accounts/time_limits/web_time_limit_error_page/resources/web_time_limit_error_page.html
INFO: Path has no substitutions: chrome/browser/plugins/plugins_resource_service.cc
INFO: Path has no substitutions: chrome/browser/resources/chromeos/accessibility/chromevox/options/options.css
INFO: Path has no substitutions: chrome/browser/resources/chromeos/accessibility/select_to_speak/options.css
INFO: Path has no substitutions: chrome/browser/resources/discards/graph_doc_template.html
INFO: Path has no substitutions: chrome/browser/supervised_user/supervised_user_error_page/resources/supervised_user_block_interstitial.html
INFO: Path has no substitutions: chrome/common/google_url_loader_throttle.cc
INFO: Path has no substitutions: components/dom_distiller/content/browser/dom_distiller_viewer_source.cc
INFO: Path has no substitutions: components/dom_distiller/core/html/preview.html
INFO: Path has no substitutions: components/domain_reliability/google_configs.cc
INFO: Path has no substitutions: components/page_load_metrics/common/page_load_metrics_util.cc
INFO: Path has no substitutions: net/base/url_util.cc
INFO: Path has no substitutions: net/dns/public/doh_provider_entry.cc
INFO: Path has no substitutions: net/tools/transport_security_state_generator/transport_security_state_generator.cc
INFO: Path has no substitutions: rlz/lib/lib_values.cc
C:\Users\e\ungoogled-chromium-windows\build\src\third_party\android_rust_toolchain\toolchain\src\stdlibs\library\stdarch\crates\stdarch-verify\arm-intrinsics.html cannot be opened for writing! Adding write permission...
INFO: Path has no substitutions: third_party/crashpad/crashpad/doc/support/crashpad_doxygen.css
INFO: Path has no substitutions: tools/md_browser/base.css
C:\Users\e\ungoogled-chromium-windows\build\src>call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat" >nul

C:\Users\e\ungoogled-chromium-windows\build\src>set DEPOT_TOOLS_WIN_TOOLCHAIN=0

C:\Users\e\ungoogled-chromium-windows\build\src>"C:\Users\e\.pyenv\pyenv-win\versions\3.6.8\python.exe" "tools\gn\bootstrap\bootstrap.py" "-o" "out\Default\gn.exe" "--skip-generate-buildfiles"
ninja: Entering directory `C:\Users\e\ungoogled-chromium-windows\build\src\out\Release\gn_build'
[195/195] LINK gn.exe

C:\Users\e\ungoogled-chromium-windows\build\src>exit
C:\Users\e\ungoogled-chromium-windows\build\src>call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat" >nul

C:\Users\e\ungoogled-chromium-windows\build\src>set DEPOT_TOOLS_WIN_TOOLCHAIN=0

C:\Users\e\ungoogled-chromium-windows\build\src>"out\Default\gn.exe" "gen" "out\Default" "--fail-on-unused-args"
Done. Made 16672 targets from 2778 files in 6698ms

C:\Users\e\ungoogled-chromium-windows\build\src>exit
C:\Users\e\ungoogled-chromium-windows\build\src>call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat" >nul

C:\Users\e\ungoogled-chromium-windows\build\src>set DEPOT_TOOLS_WIN_TOOLCHAIN=0

C:\Users\e\ungoogled-chromium-windows\build\src>"third_party\ninja\ninja.exe" "-C" "out\Default" "chrome" "chromedriver" "mini_installer"
ninja: Entering directory `out\Default'
[3889/49428] ACTION //third_party/catapult/tracing:generate_about_tracing(//build/toolchain/win:win_clang_x64)
FAILED: gen/content/browser/tracing/about_tracing.js gen/content/browser/tracing/about_tracing.html
C:/Users/e/.pyenv/pyenv-win/versions/3.6.8/python3.exe ../../third_party/catapult/tracing/bin/generate_about_tracing_contents --outdir gen/content/browser/tracing
rCSSmin exited with error code 1Traceback (most recent call last):
  File "../../third_party/catapult/tracing/bin/generate_about_tracing_contents", line 14, in <module>
    sys.exit(generate_about_tracing_contents.Main(sys.argv[1:]))
  File "C:\Users\e\ungoogled-chromium-windows\build\src\third_party\catapult\tracing\tracing_build\generate_about_tracing_contents.py", line 46, in Main
    minify=not args.no_min)
  File "C:\Users\e\ungoogled-chromium-windows\build\src\third_party\catapult\common\py_vulcanize\py_vulcanize\generate.py", line 287, in GenerateStandaloneHTMLToFile
    module.AppendHTMLContentsToFile(output_file, controller, minify=minify)
  File "C:\Users\e\ungoogled-chromium-windows\build\src\third_party\catapult\common\py_vulcanize\py_vulcanize\html_module.py", line 73, in AppendHTMLContentsToFile
    for piece in self._parser_results.YieldHTMLInPieces(ctl, minify=minify):
  File "C:\Users\e\ungoogled-chromium-windows\build\src\third_party\catapult\common\py_vulcanize\py_vulcanize\parse_html_deps.py", line 214, in YieldHTMLInPieces
    yield self.GenerateHTML(controller, minify)
  File "C:\Users\e\ungoogled-chromium-windows\build\src\third_party\catapult\common\py_vulcanize\py_vulcanize\parse_html_deps.py", line 258, in GenerateHTML
    html = controller.GetHTMLForStylesheetHRef(stylesheet_link['href'])
  File "C:\Users\e\ungoogled-chromium-windows\build\src\third_party\catapult\common\py_vulcanize\py_vulcanize\generate.py", line 282, in GetHTMLForStylesheetHRef
    text = _MinifyCSS(text)
  File "C:\Users\e\ungoogled-chromium-windows\build\src\third_party\catapult\common\py_vulcanize\py_vulcanize\generate.py", line 215, in _MinifyCSS
    sys.stderr.write(res[1])
TypeError: write() argument must be str, not bytes
[3910/49428] CXX obj/skia/skia_core_and_effects/SkCanvas.obj
ninja: build stopped: subcommand failed.

C:\Users\e\ungoogled-chromium-windows\build\src>exit
Traceback (most recent call last):
  File "build.py", line 191, in <module>
    main()
  File "build.py", line 187, in main
    'chromedriver', 'mini_installer')
  File "build.py", line 68, in _run_build_process
    **kwargs)
  File "C:\Users\e\.pyenv\pyenv-win\versions\3.6.8\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('cmd.exe', '/k')' returned non-zero exit status 1.`
details: python 3.6.8 (pyenv)
vs ver: 2019 
windows ver: 11 22000.194

**Comment by hoanghiep1x0** [comment]
run cmd with adminitrators

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently and probably lost its significance — closing.
If you have any more information to add, let us know.
