### ISSUE TITLE
Error during build fx_crypt_sha.obj

### ISSUE THREAD

**Issue by kv-gits** [ungoogled-software/ungoogled-chromium-windows#137]
```
[8196/49428] CXX obj/third_party/pdfium/core/fdrm/fdrm/fx_crypt_sha.obj
FAILED: obj/third_party/pdfium/core/fdrm/fdrm/fx_crypt_sha.obj
..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe /c ../../third_party/pdfium/core/fdrm/fx_crypt_sha.cpp /Foobj/third_party/pdfium/core/fdrm/fdrm/fx_crypt_sha.obj /nologo /showIncludes "-imsvcC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-imsvcC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-imsvcC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-imsvcC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-imsvcC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-imsvcC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-imsvcC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-imsvcC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" -DUSE_AURA=1 "-DCR_CLANG_REVISION=\"llvmorg-14-init-8033-gabb2a91b-2\"" -D_HAS_NODISCARD -D_CRT_NONSTDC_NO_WARNINGS -D_WINSOCK_DEPRECATED_NO_WARNINGS -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -D_LIBCPP_NO_AUTO_LINK -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=2 -DWIN32 -D_SECURE_ATL -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_UNICODE -DUNICODE -DNTDDI_VERSION=NTDDI_WIN10_VB -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DPNG_PREFIX -DPNG_USE_READ_MACROS -DOPJ_STATIC -DPDF_ENABLE_V8 -DPDF_ENABLE_XFA -DPDF_ENABLE_XFA_BMP -DPDF_ENABLE_XFA_GIF -DPDF_ENABLE_XFA_PNG -DPDF_ENABLE_XFA_TIFF -DPDFIUM_PRINT_TEXT_WITH_GDI "-DFT_CONFIG_MODULES_H=\"freetype-custom/freetype/config/ftmodule.h\"" "-DFT_CONFIG_OPTIONS_H=\"freetype-custom/freetype/config/ftoption.h\"" -DPDFIUM_REQUIRED_MODULES -DCHROMIUM_RESTRICT_VISIBILITY -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -I../.. -Igen -I../../buildtools/third_party/libc++ -I../../third_party/pdfium -I../../third_party/freetype/include -I../../third_party/freetype/include/freetype-custom -I../../third_party/freetype/src/include -I../../third_party/harfbuzz-ng/src/src -I../../third_party/abseil-cpp -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -fno-delete-null-pointer-checks -fno-ident -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -fcomplete-member-pointers /Gy /FS /bigobj /utf-8 /Zc:twoPhase -Wno-unknown-warning-option /Zc:sizedDealloc- /D__WRL_ENABLE_FUNCTION_STATICS__ -fmsc-version=1916 -m64 -msse3 -fansi-escape-codes /Brepro -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -ffile-compilation-dir=. -no-canonical-prefixes /W4 -Wimplicit-fallthrough -Wunreachable-code-aggressive -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wloop-analysis -Wno-unneeded-internal-declaration -Wno-nonportable-include-path -Wno-null-pointer-subtraction -Wenum-compare-conditional -Wno-psabi -Wno-ignored-pragma-optimize -Wmax-tokens /O1 /Ob2 /Oy- /Zc:inline /Gw /Oi /Z7 -gcodeview-ghash -Xclang -fuse-ctor-homing -ftrivial-auto-var-init=pattern /guard:cf /MT -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare /wd4324 /wd4577 /utf-8 -Wc++11-narrowing -Wdeprecated-copy -Wshadow -Wexit-time-destructors -Wglobal-constructors -Wno-trigraphs /TP /GR- -I../../buildtools/third_party/libc++/trunk/include /Fd"obj/third_party/pdfium/core/fdrm/fdrm_cc.pdb"
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: ..\\..\\third_party\\llvm-build\\Release+Asserts\\bin\\clang-cl.exe /c ../../third_party/pdfium/core/fdrm/fx_crypt_sha.cpp /Foobj/third_party/pdfium/core/fdrm/fdrm/fx_crypt_sha.obj /nologo /showIncludes "-imsvcC:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\ATLMFC\\include" "-imsvcC:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\include" "-imsvcC:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.8\\include\\um" "-imsvcC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt" "-imsvcC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\shared" "-imsvcC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\um" "-imsvcC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\winrt" "-imsvcC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\cppwinrt" -DUSE_AURA=1 -DCR_CLANG_REVISION=\"llvmorg-14-init-8033-gabb2a91b-2\" -D_HAS_NODISCARD -D_CRT_NONSTDC_NO_WARNINGS -D_WINSOCK_DEPRECATED_NO_WARNINGS -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -D_LIBCPP_NO_AUTO_LINK -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=2 -DWIN32 -D_SECURE_ATL -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_UNICODE -DUNICODE -DNTDDI_VERSION=NTDDI_WIN10_VB -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DPNG_PREFIX -DPNG_USE_READ_MACROS -DOPJ_STATIC -DPDF_ENABLE_V8 -DPDF_ENABLE_XFA -DPDF_ENABLE_XFA_BMP -DPDF_ENABLE_XFA_GIF -DPDF_ENABLE_XFA_PNG -DPDF_ENABLE_XFA_TIFF -DPDFIUM_PRINT_TEXT_WITH_GDI -DFT_CONFIG_MODULES_H=\"freetype-custom/freetype/config/ftmodule.h\" -DFT_CONFIG_OPTIONS_H=\"freetype-custom/freetype/config/ftoption.h\" -DPDFIUM_REQUIRED_MODULES -DCHROMIUM_RESTRICT_VISIBILITY -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -I../.. -Igen -I../../buildtools/third_party/libc++ -I../../third_party/pdfium -I../../third_party/freetype/include -I../../third_party/freetype/include/freetype-custom -I../../third_party/freetype/src/include -I../../third_party/harfbuzz-ng/src/src -I../../third_party/abseil-cpp -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -fno-delete-null-pointer-checks -fno-ident -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -fcomplete-member-pointers /Gy /FS /bigobj /utf-8 /Zc:twoPhase -Wno-unknown-warning-option /Zc:sizedDealloc- /D__WRL_ENABLE_FUNCTION_STATICS__ -fmsc-version=1916 -m64 -msse3 -fansi-escape-codes /Brepro -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -ffile-compilation-dir=. -no-canonical-prefixes /W4 -Wimplicit-fallthrough -Wunreachable-code-aggressive -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wloop-analysis -Wno-unneeded-internal-declaration -Wno-nonportable-include-path -Wno-null-pointer-subtraction -Wenum-compare-conditional -Wno-psabi -Wno-ignored-pragma-optimize -Wmax-tokens /O1 /Ob2 /Oy- /Zc:inline /Gw /Oi /Z7 -gcodeview-ghash -Xclang -fuse-ctor-homing -ftrivial-auto-var-init=pattern /guard:cf /MT -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare /wd4324 /wd4577 /utf-8 -Wc++11-narrowing -Wdeprecated-copy -Wshadow -Wexit-time-destructors -Wglobal-constructors -Wno-trigraphs /TP /GR- -I../../buildtools/third_party/libc++/trunk/include /Fdobj/third_party/pdfium/core/fdrm/fdrm_cc.pdb
1.      <eof> parser at end of file
2.      Optimizer
 #0 0x00007ff65b5f7d16 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1d37d16)
 #1 0x00007ff65b60623d (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1d4623d)
 #2 0x00007ff65b5e4f2b (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1d24f2b)
 #3 0x00007ff65b5dfcfe (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1d1fcfe)
 #4 0x00007ff65b5dffbd (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1d1ffbd)
 #5 0x00007ff65b5dff70 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1d1ff70)
 #6 0x00007ff65b5e24fd (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1d224fd)
 #7 0x00007ff65b5dff70 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1d1ff70)
 #8 0x00007ff65b5dff70 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1d1ff70)
 #9 0x00007ff65b5dff70 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1d1ff70)
#10 0x00007ff65b5dff70 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1d1ff70)
#11 0x00007ff65b5e0a0a (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1d20a0a)
#12 0x00007ff65b5dffbd (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1d1ffbd)
#13 0x00007ff65b5e33a2 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1d233a2)
#14 0x00007ff65b5de815 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1d1e815)
#15 0x00007ff65b5fc8e8 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1d3c8e8)
#16 0x00007ff65b5fdef0 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1d3def0)
#17 0x00007ff65b5fa6d4 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1d3a6d4)
#18 0x00007ff65b5f9a71 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1d39a71)
#19 0x00007ff65b5f9315 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1d39315)
#20 0x00007ff65c19db41 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x28ddb41)
#21 0x00007ff65ae53fd3 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1593fd3)
#22 0x00007ff659af3e91 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x233e91)
#23 0x00007ff65ae52ca1 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1592ca1)
#24 0x00007ff659af3ce1 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x233ce1)
#25 0x00007ff65ae5329c (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x159329c)
#26 0x00007ff65b6cd1a5 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1e0d1a5)
#27 0x00007ff65b6c874e (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1e0874e)
#28 0x00007ff65d6d6e50 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x3e16e50)
#29 0x00007ff65c868023 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x2fa8023)
#30 0x00007ff65bc4a9c2 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x238a9c2)
#31 0x00007ff65bc121bd (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x23521bd)
#32 0x00007ff65bcb8c26 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x23f8c26)
#33 0x00007ff6598c75c3 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x75c3)
#34 0x00007ff6598c47ff (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x47ff)
#35 0x00007ff65bb258c6 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x22658c6)
#36 0x00007ff65b3fd39f (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x1b3d39f)
#37 0x00007ff65bb255b7 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x22655b7)
#38 0x00007ff65ba69462 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x21a9462)
#39 0x00007ff65ba69a09 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x21a9a09)
#40 0x00007ff65ba4bf26 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x218bf26)
#41 0x00007ff6598c411d (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x411d)
#42 0x00007ff65d6f67b8 (E:\src_builds\chromium\ungoogled-chromium-windows\build\src\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe+0x3e367b8)
#43 0x00007ffc3ecf7034 (C:\WINDOWS\System32\KERNEL32.DLL+0x17034)
#44 0x00007ffc40942651 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x52651)
clang-cl: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 13.0.0
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: ..\..\third_party\llvm-build\Release+Asserts\bin
clang-cl: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-cl: note: diagnostic msg: ../../tools/clang/crashreports\fx_crypt_sha-8d1e8a.cpp
clang-cl: note: diagnostic msg: ../../tools/clang/crashreports\fx_crypt_sha-8d1e8a.sh
clang-cl: note: diagnostic msg:

********************
[8205/49428] ACTION //third_party/devtools-frontend/src/f...ypoint-meta-tsconfig(//build/toolchain/win:win_clang_x64) ninja: build stopped: subcommand failed.

E:\src_builds\chromium\ungoogled-chromium-windows\build\src>exit
Traceback (most recent call last):
  File "E:\src_builds\chromium\ungoogled-chromium-windows\build.py", line 193, in <module>
    main()
  File "E:\src_builds\chromium\ungoogled-chromium-windows\build.py", line 188, in main
    _run_build_process('third_party\\ninja\\ninja.exe', '-C', 'out\\Default', 'chrome',
  File "E:\src_builds\chromium\ungoogled-chromium-windows\build.py", line 66, in _run_build_process
    subprocess.run(('cmd.exe', '/k'),
  File "C:\Users\Verywellyo\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('cmd.exe', '/k')' returned non-zero exit status 1.
```

There was simillar issue with old clang version, but how to define right version for the current build?

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently and probably lost its significance — closing.
If you have any more information to add, let us know.
