### ISSUE TITLE
DeprecationWarning and UnicodeDecodeError

### ISSUE THREAD

**Issue by playgithub** [ungoogled-software/ungoogled-chromium-windows#157]
### Env
Python 3.10.5

### Logs
```cmd
[903/51773] ACTION //chrome/elevation_service:elevation_service_idl_idl_action(//build/toolchain/win:win_clang_x64)
D:\ungoogled-chromium-windows\build\src\build\toolchain\win\midl.py:10: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.file_util
[1588/51773] ACTION //google_update:google_update_idl_action(//build/toolchain/win:win_clang_x64)
D:\ungoogled-chromium-windows\build\src\build\toolchain\win\midl.py:10: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.file_util
[4838/51773] ACTION //third_party/devtools-frontend/src/fr...rypoint-bundle-bundle(//build/toolchain/win:win_clang_x64) Exception in thread Thread-2 (_readerthread):
Traceback (most recent call last):
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1497, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 2: illegal multibyte sequence
```

### More Info
They don't block the building.

### Question
Any bad side effect for the final binaries?

**Comment by teeminus** [comment]
The deprecation warning does not affect the build process.

Regarding the Unicode decode error: I have not seen this error before and no idea what cause it or how to fix it.

**Comment by playgithub** [comment]
The build passed, and it works well.

**Comment by Nifury** [comment]
The default encoding is gbk on the Chinese version of Windows. 
You need to set `encoding` for Popen or change the default encoding to utf-8 to fix the decode error.

**Comment by playgithub** [comment]
> You need to set `encoding` for Popen

Which script?
