### ISSUE TITLE
ninja: error: unknown target 'gn'. I got the same error, can anyone tell me how to fix it?

### ISSUE THREAD

**Issue by hoanghiep1x0** [ungoogled-software/ungoogled-chromium-windows#189]
```
./tools/gn/bootstrap/bootstrap.py --skip-generate-buildfiles -j4 -o out/Default/
ninja: error: unknown target 'gn'
ninja: Entering directory `C:\Users\MACBOOK\ungoogled-chromium\build\src\out\Release\gn_build'
Traceback (most recent call last):
  File "./tools/gn/bootstrap/bootstrap.py", line 144, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./tools/gn/bootstrap/bootstrap.py", line 127, in main
    [ninja_binary, '-C', gn_build_dir, '-w', 'dupbuild=err', '-j'+str(options.jobs), 'gn'])
  File "C:\tools\python2\lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-C', 'C:\\Users\\MACBOOK\\ungoogled-chromium\\build\\src\\out\\Release\\gn_build', '-w', 'dupbuild=err', '-j4', 'gn']' returned non-zero exit status 1
```

i tried almost every tutorial but don't know how to debug.

**Comment by hoanghiep1x0** [comment]
@Nifury I tried following all the instructions but got the same error. I tried to fix it many times before asking..

**Comment by Nifury** [comment]
`./tools/gn/bootstrap/bootstrap.py --skip-generate-buildfiles -j4 -o out/Default/` indicates you are using ungoogled-chromium repo instead of ungoogled-chromium-windows.

**Comment by hoanghiep1x0** [comment]
@Nifury Yes. An error similar to ungoogled-chromium-windows and I try to reproduce the problem by separating the run statement with ungoogled-chromium.
A similar error is emitted.

**Comment by teeminus** [comment]
Can you please post the output of the command `py --version`?

**Comment by hoanghiep1x0** [comment]
@teeminus can you refer to help me
C:\Users\Administrator>python --version
Python 3.8.10
C:\Users\Administrator>where python
C:\tools\python3\python.exe
C:\Users\Administrator>python3 --version
Python 3.8.10

system variable has been added as instructed:
vs2019_install=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
WINDOWSSDKDIR=C:\Program Files (x86)\Windows Kits\10
GYP_MSVS_VERSION=2019

then run the command in cmd.exe (as administrator):

git clone --recurse-submodules https://github.com/ungoogled-software/ungoogled-chromium-windows.git

cd ungoogled-chromium-windows

py build.py

1 error after that

```
C:\ungoogled-chromium-windows\build\src>"C:\tools\python3\python.exe" "tools\gn\bootstrap\bootstrap.py" "-o" "out\Default\gn.exe" "--skip-generate-buildfiles"
ninja: Entering directory `C:\ungoogled-chromium-windows\build\src\out\Release\gn_build'
[196/196] LINK gn.exe

C:\ungoogled-chromium-windows\build\src>exit
C:\ungoogled-chromium-windows\build\src>call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat" >nul

C:\ungoogled-chromium-windows\build\src>set DEPOT_TOOLS_WIN_TOOLCHAIN=0

C:\ungoogled-chromium-windows\build\src>"out\Default\gn.exe" "gen" "out\Default" "--fail-on-unused-args"
Traceback (most recent call last):
  File "C:/ungoogled-chromium-windows/build/src/build/toolchain/win/setup_toolchain.py", line 315, in <module>
    main()
  File "C:/ungoogled-chromium-windows/build/src/build/toolchain/win/setup_toolchain.py", line 273, in main
    env = _LoadToolchainEnv(cpu, toolchain_root, win_sdk_path, target_store)
  File "C:/ungoogled-chromium-windows/build/src/build/toolchain/win/setup_toolchain.py", line 189, in _LoadToolchainEnv
    return _ExtractImportantEnvironment(variables)
  File "C:/ungoogled-chromium-windows/build/src/build/toolchain/win/setup_toolchain.py", line 67, in _ExtractImportantEnvironment
    raise Exception(
Exception: Path "C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\shared" from environment variable "include" does not exist. Make sure the necessary SDK is installed.
ERROR at //build/toolchain/win/toolchain.gni:499:24: Script returned non-zero exit code.
  win_toolchain_data = exec_script("//build/toolchain/win/setup_toolchain.py",
                       ^----------
Current dir: C:/ungoogled-chromium-windows/build/src/out/Default/
Command: C:/tools/python3/python3.exe C:/ungoogled-chromium-windows/build/src/build/toolchain/win/setup_toolchain.py "C:\Program Files (x86)/Microsoft Visual Studio/2019/Community" "C:\Program Files (x86)\Windows Kits\10" "C:\Windows\System32;C:\Windows\SysWOW64;Arm64Unused" win x86 environment.x86
Returned 1.
See //build/toolchain/win/BUILD.gn:34:3: whence it was called.
  win_toolchains("x86") {
  ^----------------------
See //BUILD.gn:82:1: which caused the file to be included.
group("gn_all") {
^----------------

C:\ungoogled-chromium-windows\build\src>exit
Traceback (most recent call last):
  File "build.py", line 240, in <module>
    main()
  File "build.py", line 226, in main
    _run_build_process('out\\Default\\gn.exe', 'gen', 'out\\Default', '--fail-on-unused-args')
  File "build.py", line 67, in _run_build_process
    subprocess.run(('cmd.exe', '/k'),
  File "C:\tools\python3\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('cmd.exe', '/k')' returned non-zero exit status 1.

C:\ungoogled-chromium-windows>
```

**Comment by teeminus** [comment]
Based on your deleted comment: Do you use `cmd.exe` or the `Developer Command Prompt for VS`?

**Comment by hoanghiep1x0** [comment]
@teeminus can you refer to help me
C:\Users\Administrator>python --version
Python 3.8.10
C:\Users\Administrator>where python
C:\tools\python3\python.exe
C:\Users\Administrator>python3 --version
Python 3.8.10
system variable has been added as instructed:
vs2019_install=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
WINDOWSSDKDIR=C:\Program Files (x86)\Windows Kits\10
GYP_MSVS_VERSION=2019
 I'm trying to re-initialize the problem. There's been a problem with windowskits/10/20348,288 I'll get back to you.

**Comment by hoanghiep1x0** [comment]
i use "cmd" run with adminitrator

**Comment by teeminus** [comment]
Try using the `Developer Command Prompt for VS`.

**Comment by hoanghiep1x0** [comment]
Sorry I already know where the problem is depot_tools and path run command ungoogled-software not by ungoogled-software-windows.

1. is because python3 and depot_tools path of depot_tools on top position environment variable. according to instructions depot_tools is deprecated as google_chromium build.
2. is because the windowkit version with the appropriate OS does not exist.
windowkit/10/19045.2251 is loaded automatically while os is 20348.288.
3. should run with "cmd.exe administrator"

C:\Users\Administrator>python --version
Python 3.8.10
C:\Users\Administrator>where python
C:\tools\python3\python.exe
C:\Users\Administrator>python3 --version
Python 3.8.10

system variable has been added as instructed:
vs2019_install=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
WINDOWSSDKDIR=C:\Program Files (x86)\Windows Kits\10
GYP_MSVS_VERSION=2019

Note exists OS version build when installing with Microsoft Visual Studio.
"C:\Program Files (x86)\Windows Kits\10\ + OS_VERSION".

then run the command in cmd.exe (as administrator):

git clone --recurse-submodules https://github.com/ungoogled-software/ungoogled-chromium-windows.git

cd ungoogled-chromium-windows

py build.py

then it should work properly.

Sorry for wasting your time, thanks for your help.

**Comment by joja16** [comment]
Are you still developing using VS2019?
