### ISSUE TITLE
Build error :-(

### ISSUE THREAD

**Issue by hariskar** [ungoogled-software/ungoogled-chromium-windows#198]
Sorry if this place is inapropriate for me to write about this problem..
Compilation stops at about 26000/54000 whatever I tried..
This is the error I get. Any help please?

`C:\Users\haris\ungoogled-chromium-windows\build\src>exit
C:\Users\haris\ungoogled-chromium-windows\build\src>call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat" >nul

C:\Users\haris\ungoogled-chromium-windows\build\src>set DEPOT_TOOLS_WIN_TOOLCHAIN=0

C:\Users\haris\ungoogled-chromium-windows\build\src>"third_party\ninja\ninja.exe" "-C" "out\Default" "chrome" "chromedriver" "mini_installer"
ninja: Entering directory `out\Default'
[24917/54784] CXX obj/components/domain_reliability/domain_reliability/google_configs.obj
../../components/domain_reliability/google_configs.cc(16,8): warning: unused variable 'is_www_subdomain' [-Wunused-variable]
  bool is_www_subdomain =
       ^
1 warning generated.
[24934/54784] CXX obj/components/domain_reliability/domain_reliability/uploader.obj
../../components/domain_reliability/uploader.cc(92,9): warning: code will never be executed [-Wunreachable-code]
        net::DefineNetworkTrafficAnnotation("domain_reliability_report_upload",
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../components/domain_reliability/uploader.cc(83,9): note: silence by adding parentheses to mark code as explicitly dead
    if (true) {
        ^
        /* DISABLES CODE */ ( )
1 warning generated.
[26000/54784] ACTION //chrome/browser/ui/webui/tab_search:mojo_bindings_js__generator(//build/toolchain/win:win_clang_x64)
FAILED: gen/chrome/browser/ui/webui/tab_search/tab_search.mojom.js gen/chrome/browser/ui/webui/tab_search/tab_search.mojom.m.js gen/chrome/browser/ui/webui/tab_search/tab_search.mojom-lite.js gen/chrome/browser/ui/webui/tab_search/tab_search.mojom-lite-for-compile.js gen/mojom-webui/chrome/browser/ui/webui/tab_search/tab_search.mojom-webui.js
C:/Python311/python3.exe ../../mojo/public/tools/bindings/mojom_bindings_generator.py --use_bundled_pylibs -o gen generate -d ../../ -I ../../ --bytecode_path gen/mojo/public/tools/bindings --filelist=__chrome_browser_ui_webui_tab_search_mojo_bindings_js__generator___build_toolchain_win_win_clang_x64__rule..rsp -g javascript --scrambled_message_id_salt_path ../../chrome/VERSION
Traceback (most recent call last):
  File "C:\Users\haris\ungoogled-chromium-windows\build\src\mojo\public\tools\bindings\mojom_bindings_generator.py", line 417, in <module>
    ret = main()
          ^^^^^^
  File "C:\Users\haris\ungoogled-chromium-windows\build\src\mojo\public\tools\bindings\mojom_bindings_generator.py", line 412, in main
    return args.func(args, remaining_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\haris\ungoogled-chromium-windows\build\src\mojo\public\tools\bindings\mojom_bindings_generator.py", line 274, in _Generate
    processor._GenerateModule(
  File "C:\Users\haris\ungoogled-chromium-windows\build\src\mojo\public\tools\bindings\mojom_bindings_generator.py", line 242, in _GenerateModule
    generator.GenerateFiles(filtered_args)
  File "C:\Users\haris\ungoogled-chromium-windows\build\src\mojo\public\tools\bindings\generators\mojom_js_generator.py", line 433, in GenerateFiles
    self.WriteWithComment(self._GenerateWebUiModule(),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\haris\ungoogled-chromium-windows\build\src\mojo\public\tools\mojom\mojom\generate\template_expander.py", line 34, in GeneratorInternal
    parameters = generator(*args, **kwargs2)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\haris\ungoogled-chromium-windows\build\src\mojo\public\tools\bindings\generators\mojom_js_generator.py", line 412, in _GenerateWebUiModule
    return self._GetParameters(for_webui_module=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\haris\ungoogled-chromium-windows\build\src\mojo\public\tools\bindings\generators\mojom_js_generator.py", line 299, in _GetParameters
    self._GetJsModuleImports(for_webui_module=for_webui_module),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\haris\ungoogled-chromium-windows\build\src\mojo\public\tools\bindings\generators\mojom_js_generator.py", line 1042, in _GetJsModuleImports
    os.path.relpath(
  File "<frozen ntpath>", line 758, in relpath
ValueError: path is on mount '', start on mount 'C:'
[26005/54784] CXX obj/v8/cppgc_base/heap-growing.obj
ninja: build stopped: subcommand failed.

C:\Users\haris\ungoogled-chromium-windows\build\src>exit
Traceback (most recent call last):
  File "C:\Users\haris\ungoogled-chromium-windows\build.py", line 240, in <module>
    main()
  File "C:\Users\haris\ungoogled-chromium-windows\build.py", line 235, in main
    _run_build_process('third_party\\ninja\\ninja.exe', '-C', 'out\\Default', 'chrome',
  File "C:\Users\haris\ungoogled-chromium-windows\build.py", line 67, in _run_build_process
    subprocess.run(('cmd.exe', '/k'),
  File "C:\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('cmd.exe', '/k')' returned non-zero exit status 1.`

**Comment by greenozon** [comment]
some clues might be over here
https://github.com/python/cpython/issues/51444

**Comment by joey04** [comment]
I got the exact same failure building a different version.

Thankfully, [this video](https://www.youtube.com/watch?v=318tXgnhIXI) (slowed down) revealed the solution:

```
Install Python for All Users

c:\>where py
C:\Windows\py.exe

c:\>where python
C:\Program Files\Python39\python.exe

Copy this file and name it python3.exe; some Chromium scripts need it.

c:\>where python3
C:\Program Files\Python39\python3.exe

Then run scripts with installed python (not py)
> python  build.py
```

My build completed without any further problems.
