### ISSUE TITLE
Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

### ISSUE THREAD

**Issue by danieljames0210** [ungoogled-software/ungoogled-chromium-windows#202]
Hi, I try input command "py build.py" and get error : curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
ERROR: curl failed. Re-run the download command to resume downloading.
How to fix it??

H:\chromium-ungoogle\ungoogled-chromium-windows>py build.py
INFO: Downloading required files...
INFO: Downloading "chromium" to "chromium-109.0.5414.120.tar.xz" ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
ERROR: curl failed. Re-run the download command to resume downloading.
Traceback (most recent call last):
  File "H:\chromium-ungoogle\ungoogled-chromium-windows\build.py", line 240, in <module>
    main()
  File "H:\chromium-ungoogle\ungoogled-chromium-windows\build.py", line 158, in main
    downloads.retrieve_downloads(download_info, downloads_cache, True,
  File "H:\chromium-ungoogle\ungoogled-chromium-windows\ungoogled-chromium\utils\downloads.py", line 282, in retrieve_downloads
    _download_if_needed(download_path, download_properties.url, show_progress,
  File "H:\chromium-ungoogle\ungoogled-chromium-windows\ungoogled-chromium\utils\downloads.py", line 229, in _download_if_needed
    raise exc
  File "H:\chromium-ungoogle\ungoogled-chromium-windows\ungoogled-chromium\utils\downloads.py", line 226, in _download_if_needed
    subprocess.run(['curl', '-L', '-o', str(tmp_file_path), '-C', '-', url], check=True)
  File "C:\Users\cuong\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['curl', '-L', '-o', 'H:\\chromium-ungoogle\\ungoogled-chromium-windows\\build\\download_cache\\chromium-109.0.5414.120.tar.xz.partial', '-C', '-', 'https://commondatastorage.googleapis.com/chromium-browser-official/chromium-109.0.5414.120.tar.xz']' returned non-zero exit status 35.

Thank!!

**Comment by networkException** [comment]
Sounds like an issue with certificates on your system. Does rerunning the command produce the same error?

**Comment by joja16** [comment]
I also got the same error, I have re-run it many times but still the error.
INFO: Verifying hashes for "nodejs" ...
INFO: Unpacking downloads...
INFO: Unpacking "chromium" to ./ ...
ERROR: Temporary unpacking directory already exists: E:\chromium\ungoogled-chromium-windows\build\src\chromium-110.0.5481.100
Traceback (most recent call last):
  File "E:\chromium\ungoogled-chromium-windows\build.py", line 240, in <module>
    main()
  File "E:\chromium\ungoogled-chromium-windows\build.py", line 172, in main
    downloads.unpack_downloads(download_info, downloads_cache, source_tree, extractors)
  File "E:\chromium\ungoogled-chromium-windows\ungoogled-chromium\utils\downloads.py", line 343, in unpack_downloads
    extractor_func(
  File "E:\chromium\ungoogled-chromium-windows\ungoogled-chromium\utils\_extraction.py", line 225, in extract_tar_file
    _extract_tar_with_7z(sevenzip_bin, archive_path, output_dir, relative_to)
  File "E:\chromium\ungoogled-chromium-windows\ungoogled-chromium\utils\_extraction.py", line 103, in _extract_tar_with_7z
    raise ExtractionError()
_extraction.ExtractionError

**Comment by phungthelam1996** [comment]
> 

I added `extractor = winrar` to ungoogled-chromium/downloads.ini to fixed it.
