### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by gz83** [ungoogled-software/ungoogled-chromium-windows#204]
Compile with the latest tag, the compiler prompts the following error, and the compilation is interrupted

[24836/53767] ACTION //chrome/browser/ui/webui/tab_search:...indings_ts__generator(//build/toolchain/win:win_clang_x64)
FAILED: gen/chrome/browser/ui/webui/tab_search/tab_search.mojom-webui.ts
C:/Users/Administrator/AppData/Local/Programs/Python/Python311/python3.exe ../../mojo/public/tools/bindings/mojom_bindings_generator.py --use_bundled_pylibs -o gen generate -d ../../ -I ../../ --bytecode_path gen/mojo/public/tools/bindings --filelist=__chrome_browser_ui_webui_tab_search_mojo_bindings_ts__generator___build_toolchain_win_win_clang_x64__rule..rsp -g typescript --scrambled_message_id_salt_path ../../chrome/VERSION
Traceback (most recent call last):
  File "E:\src\ungoogled-chromium-windows\build\src\mojo\public\tools\bindings\mojom_bindings_generator.py", line 417, in <module>
    ret = main()
          ^^^^^^
  File "E:\src\ungoogled-chromium-windows\build\src\mojo\public\tools\bindings\mojom_bindings_generator.py", line 412, in main
    return args.func(args, remaining_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\src\ungoogled-chromium-windows\build\src\mojo\public\tools\bindings\mojom_bindings_generator.py", line 274, in _Generate
    processor._GenerateModule(
  File "E:\src\ungoogled-chromium-windows\build\src\mojo\public\tools\bindings\mojom_bindings_generator.py", line 242, in _GenerateModule
    generator.GenerateFiles(filtered_args)
  File "E:\src\ungoogled-chromium-windows\build\src\mojo\public\tools\bindings\generators\mojom_ts_generator.py", line 256, in GenerateFiles
    self.WriteWithComment(self._GenerateWebUiModule(),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\src\ungoogled-chromium-windows\build\src\mojo\public\tools\mojom\mojom\generate\template_expander.py", line 34, in GeneratorInternal
    parameters = generator(*args, **kwargs2)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\src\ungoogled-chromium-windows\build\src\mojo\public\tools\bindings\generators\mojom_ts_generator.py", line 242, in _GenerateWebUiModule
    return self._GetParameters()
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\src\ungoogled-chromium-windows\build\src\mojo\public\tools\bindings\generators\mojom_ts_generator.py", line 208, in _GetParameters
    self._GetJsModuleImports(),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\src\ungoogled-chromium-windows\build\src\mojo\public\tools\bindings\generators\mojom_ts_generator.py", line 577, in _GetJsModuleImports
    os.path.relpath(
  File "<frozen ntpath>", line 754, in relpath
ValueError: path is on mount '\\\\tab_group_types.mojom-webui.js', start on mount 'E:'
[24847/53767] ACTION //components/strings:components_strings_grit(//build/toolchain/win:win_clang_x64)
ninja: build stopped: subcommand failed.

E:\src\ungoogled-chromium-windows\build\src>exit
Traceback (most recent call last):
  File "E:\src\ungoogled-chromium-windows\build.py", line 240, in <module>
    main()
  File "E:\src\ungoogled-chromium-windows\build.py", line 235, in main
    _run_build_process('third_party\\ninja\\ninja.exe', '-C', 'out\\Default', 'chrome',
  File "E:\src\ungoogled-chromium-windows\build.py", line 67, in _run_build_process
    subprocess.run(('cmd.exe', '/k'),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('cmd.exe', '/k')' returned non-zero exit status 1.

E:\src\ungoogled-chromium-windows>cd build\src\third_party\ninja

**Comment by joey04** [comment]
Looks like a duplicate of #198
