### ISSUE TITLE
miniinstaller not found

### ISSUE THREAD

**Issue by infinitegame111** [ungoogled-software/ungoogled-chromium-windows#224]
When running py build.py --cl it worked fine but out of no ware this happened.

FAILED: gen/chrome/browser/resources/settings/resources_grit.d.stamp gen/chrome/grit/settings_resources.h gen/chrome/grit/settings_resources_map.cc gen/chrome/grit/settings_resources_map.h gen/chrome/settings_resources.pak gen/chrome/settings_resources.pak.info
C:/Python39/python3.exe ../../tools/grit/grit.py -i gen/chrome/browser/resources/settings/resources.grd build -o gen/chrome --depdir . --depfile gen/chrome/browser/resources/settings/resources_grit.d --write-only-new=1 --depend-on-stamp -D DEVTOOLS_GRD_PATH=gen/third_party/devtools-frontend/src/front_end/devtools_resources -D SHARED_INTERMEDIATE_DIR=gen -D _google_chrome=false -D _is_chrome_for_testing_branded=false -D chromeos_ash=false -D chromeos_lacros=false -D reven=false -D toolkit_views=true -D use_aura=true -D use_ozone=false -D use_titlecase=false -D scale_factors=2x -E root_gen_dir=gen -E root_src_dir=../../ -E CHROMIUM_BUILD=chromium -D chrome_root_store_supported=true -D enable_arcore=false -D enable_printing=true -D enable_extensions=true -D enable_hangout_services_extension=false -D enable_nacl=false -D enable_dice_support=true -D enable_pdf=true -D enable_print_preview=true -D enable_supervised_users=false -D enable_vr=false -D enable_webui_certificate_viewer=true -D enable_webui_tab_strip=true -D is_official_build=true -D safe_browsing_mode=0 -D optimize_webui=true -D use_nss_certs=false -f gen/tools/gritsettings/default_resource_ids -p ../../tools/gritsettings/startup_resources_win.txt --assert-file-list obj/chrome/browser/resources/settings/resources_expected_outputs.txt --allowlist-support
Error processing node <?xml version="1.0" encoding="UTF-8"?>
<include file="${root_src_dir}/chrome/browser/resources/settings/images/safe_browsing_banner_dark.svg" name="IDR_SETTINGS_IMAGES_SAFE_BROWSING_BANNER_DARK_SVG" resource_path="images/safe_browsing_banner_dark.svg" type="BINDATA" use_base_dir="false" />: [Errno 2] No such file or directory: '..\\..\\chrome\\browser\\resources\\settings\\images\\safe_browsing_banner_dark.svg'
Traceback (most recent call last):
  File "C:\Users\ryana\ungoogled-chromium-windows\build\src\tools\grit\grit.py", line 28, in <module>
    sys.exit(grit.grit_runner.Main(sys.argv[1:]))
  File "C:\Users\ryana\ungoogled-chromium-windows\build\src\tools\grit\grit\grit_runner.py", line 313, in Main
    return toolobject.Run(options, args[1:])
  File "C:\Users\ryana\ungoogled-chromium-windows\build\src\tools\grit\grit\tool\build.py", line 272, in Run
    self.Process()
  File "C:\Users\ryana\ungoogled-chromium-windows\build\src\tools\grit\grit\tool\build.py", line 407, in Process
    self.ProcessNode(self.res, output, tmpfile)
  File "C:\Users\ryana\ungoogled-chromium-windows\build\src\tools\grit\grit\tool\build.py", line 331, in ProcessNode
    formatted = formatter(node, output_node.GetLanguage(), output_dir=base_dir)
  File "C:\Users\ryana\ungoogled-chromium-windows\build\src\tools\grit\grit\format\data_pack.py", line 87, in Format
    value = node.GetDataPackValue(lang, util.BINARY)
  File "C:\Users\ryana\ungoogled-chromium-windows\build\src\tools\grit\grit\node\include.py", line 109, in GetDataPackValue
    data = util.ReadFile(filename, util.BINARY)
  File "C:\Users\ryana\ungoogled-chromium-windows\build\src\tools\grit\grit\util.py", line 210, in ReadFile
    with open(filename, mode, encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: '..\\..\\chrome\\browser\\resources\\settings\\images\\safe_browsing_banner_dark.svg'
ninja: build stopped: subcommand failed.

C:\Users\ryana\ungoogled-chromium-windows\build\src>exit
Traceback (most recent call last):
  File "C:\Users\ryana\ungoogled-chromium-windows\package.py", line 70, in <module>
    main()
  File "C:\Users\ryana\ungoogled-chromium-windows\package.py", line 48, in main
    shutil.copyfile('build/src/out/Default/mini_installer.exe',
  File "C:\Python39\lib\shutil.py", line 265, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'build/src/out/Default/mini_installer.exe'

**Comment by infinitegame111** [comment]
This issue was resolved after further inspection, sorry.
