### ISSUE TITLE
issues with py build.py

### ISSUE THREAD

**Issue by infinitegame111** [ungoogled-software/ungoogled-chromium-windows#228]
When running py build.py [in admin cmd] this occured:

 45 25.7M   45 11.6M    0     0  26042      0  0:17:15  0:07:50  0:09:25  225k
curl: (18) transfer closed with 14709224 bytes remaining to read
ERROR: curl failed. Re-run the download command to resume downloading.
Traceback (most recent call last):
  File "c:\Users\ryana\ungoogled-chromium-windows\build.py", line 239, in <module>
    main()
  File "c:\Users\ryana\ungoogled-chromium-windows\build.py", line 157, in main
    downloads.retrieve_downloads(download_info, downloads_cache, True,
  File "C:\Users\ryana\ungoogled-chromium-windows\ungoogled-chromium\utils\downloads.py", line 282, in retrieve_downloads
    _download_if_needed(download_path, download_properties.url, show_progress,
  File "C:\Users\ryana\ungoogled-chromium-windows\ungoogled-chromium\utils\downloads.py", line 229, in _download_if_needed
    raise exc
  File "C:\Users\ryana\ungoogled-chromium-windows\ungoogled-chromium\utils\downloads.py", line 226, in _download_if_needed
    subprocess.run(['curl', '-L', '-o', str(tmp_file_path), '-C', '-', url], check=True)
  File "C:\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['curl', '-L', '-o', 'C:\\Users\\ryana\\ungoogled-chromium-windows\\build\\download_cache\\node-v16.17.0-win-x64.zip.partial', '-C', '-', 'https://nodejs.org/dist/v16.17.0/node-v16.17.0-win-x64.zip']' returned non-zero exit status 18.

can anyone help me? I do have 7zip installed

**Comment by PF4Public** [comment]
Is this an issue with ungoogled-chromium?
