### ISSUE TITLE
Error while building: ValueError: path is on mount '', start on mount 'C:'

### ISSUE THREAD

**Issue by prolium** [ungoogled-software/ungoogled-chromium-windows#248]
I'm trying to build on Windows 10, but I'm always getting this error:
<details>
  <summary>Error log</summary>
  
```
ninja: Entering directory `out\Default'
[14174/55206] ACTION //chrome/browser/ui/webui/tab_search:mojo_bindings_ts__generator(//build/toolchain/win:win_clang_x64)
FAILED: gen/chrome/browser/ui/webui/tab_search/tab_search.mojom-webui.ts
C:/Programs/VSCode/Python/python-3.11.1.amd64/python3.exe ../../mojo/public/tools/bindings/mojom_bindings_generator.py --use_bundled_pylibs -o gen generate -d ../../ -I ../../ --bytecode_path gen/mojo/public/tools/bindings --filelist=__chrome_browser_ui_webui_tab_search_mojo_bindings_ts__generator___build_toolchain_win_win_clang_x64__rule..rsp -g typescript --scrambled_message_id_salt_path ../../chrome/VERSION
Traceback (most recent call last):
  File "C:\u\build\src\mojo\public\tools\bindings\mojom_bindings_generator.py", line 418, in <module>
    ret = main()
          ^^^^^^
  File "C:\u\build\src\mojo\public\tools\bindings\mojom_bindings_generator.py", line 413, in main
    return args.func(args, remaining_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\u\build\src\mojo\public\tools\bindings\mojom_bindings_generator.py", line 275, in _Generate
    processor._GenerateModule(
  File "C:\u\build\src\mojo\public\tools\bindings\mojom_bindings_generator.py", line 243, in _GenerateModule
    generator.GenerateFiles(filtered_args)
  File "C:\u\build\src\mojo\public\tools\bindings\generators\mojom_ts_generator.py", line 264, in GenerateFiles
    self.WriteWithComment(self._GenerateWebUiModule(),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\u\build\src\mojo\public\tools\mojom\mojom\generate\template_expander.py", line 34, in GeneratorInternal
    parameters = generator(*args, **kwargs2)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\u\build\src\mojo\public\tools\bindings\generators\mojom_ts_generator.py", line 250, in _GenerateWebUiModule
    return self._GetParameters()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\u\build\src\mojo\public\tools\bindings\generators\mojom_ts_generator.py", line 216, in _GetParameters
    self._GetJsModuleImports(),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\u\build\src\mojo\public\tools\bindings\generators\mojom_ts_generator.py", line 617, in _GetJsModuleImports
    os.path.relpath(
  File "<frozen ntpath>", line 758, in relpath
ValueError: path is on mount '', start on mount 'C:'
[14195/55206] ACTION //chrome/app:generated_resources_grit(//build/toolchain/win:win_clang_x64)
ninja: build stopped: subcommand failed.
```

</details>

Reading online a little bit, this seems a known issue when an assumption is made that paths are always rooted from a grand parent like `/` on Linux, this is certainly not the case on Windows since a drive letter is the root and there are usually many drives, hence many root paths.

The script `mojom_ts_generator.py` seems to be trying to create a relative path from 2 completely irrelevant paths, ex: creating a relative path for `C:\Tools\my tool\my dir` using a base/root path `D:\another drive\which\fails`.
Start mount point `C:\` is my current directory as you can see in the logs, but the empty path mount string is weird because usually this error looks like this:
`ValueError: path is on mount 'E:', start on mount 'C:'` 

I apologize for not providing any useful feedback or any recommendations since this my first time building the project and it's overwhelming.

* OS: Windows 10 22H2 (v19045)
* Python: v3.11.1.amd64
* Visual Studio: 2022 + Windows SDK + Windows Driver Kit (WDK) + MFC/ATL

**Comment by Nifury** [comment]
#245
Python 3.11 and above is not supported.
