### ISSUE TITLE
trying to update chromium to newest release or apply patches gives errors

### ISSUE THREAD

**Issue by infinitegame111** [ungoogled-software/ungoogled-chromium-windows#298]
When running the commands for updating packages in developer info section of the readme I am getting errors for the ./update_patches.sh solution. fix when # ./devutils/check_patch_files.sh
++++ readlink -f ./devutils/check_patch_files.sh
+++ dirname /c/users/ryana/ungoogled-chromium-windows/devutils/check_patch_files.sh
++ dirname /c/users/ryana/ungoogled-chromium-windows/devutils
+ PLATFORM_ROOT=/c/users/ryana/ungoogled-chromium-windows
+ UNGOOGLED_REPO=/c/users/ryana/ungoogled-chromium-windows/ungoogled-chromium
+ /c/users/ryana/ungoogled-chromium-windows/ungoogled-chromium/devutils/check_patch_files.py -p /c/users/ryana/ungoogled-chromium-windows/patches
Traceback (most recent call last):
  File "/c/users/ryana/ungoogled-chromium-windows/ungoogled-chromium/devutils/check_patch_files.py", line 140, in <module>
    main()
  File "/c/users/ryana/ungoogled-chromium-windows/ungoogled-chromium/devutils/check_patch_files.py", line 130, in main
    warnings |= check_patch_readability(args.patches)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/c/users/ryana/ungoogled-chromium-windows/ungoogled-chromium/devutils/check_patch_files.py", line 57, in check_patch_readability
    for patch_path in _read_series_file(patches_dir, series_path, join_dir=True):
  File "/c/users/ryana/ungoogled-chromium-windows/ungoogled-chromium/devutils/check_patch_files.py", line 42, in _read_series_file
    for entry in parse_series(patches_dir / series_file):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/c/users/ryana/ungoogled-chromium-windows/ungoogled-chromium/utils/_common.py", line 124, in parse_series
    with series_path.open(encoding=ENCODING) as series_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/c/users/ryana/ungoogled-chromium-windows/patches/series'
 running ./devutils/check_patch_files.sh
 ungooled chromium windows I can't find a fix for this from any site/docs. I have tried to clone mutiple ways the one with this error was git cloned following the readme in the ungoogled chromium windows repo

**Comment by teeminus** [comment]
There were some changes in README lately to reflect some changes in the patch update procedure. Did you follow the latest patch update procedure? The old one will no longer work as the series file has been renamed (which would result in an error like you described).
