### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by yiwuaaa** [ungoogled-software/ungoogled-chromium-windows#306]
When I run python3 build.py：The system cannot find the path specified.
Looks like a gclient sync error.
Help me, please.

INFO: Cloning gn
Cloning into 'build\src\uc_staging\gn'...
remote: Total 32636 (delta 17202), reused 32636 (delta 17202)
Receiving objects: 100% (32636/32636), 33.16 MiB | 20.88 MiB/s, done.
Resolving deltas: 100% (17202/17202), done.
INFO: Running gsync
The system cannot find the path specified.
Traceback (most recent call last):
  File "C:\Program Files\Microsoft Visual Studio\2022\Community\ungoogled-chromium-windows\ungoogled-chromium\utils\clone.py", line 294, in <module>
    main()
  File "C:\Program Files\Microsoft Visual Studio\2022\Community\ungoogled-chromium-windows\ungoogled-chromium\utils\clone.py", line 290, in main
    clone(args)
  File "C:\Program Files\Microsoft Visual Studio\2022\Community\ungoogled-chromium-windows\ungoogled-chromium\utils\clone.py", line 124, in clone
    run([str(gcpath), 'sync', '-f', '-D', '-R', '--no-history', '--nohooks'], check=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['build\\src\\uc_staging\\depot_tools\\gclient.bat', 'sync', '-f', '-D', '-R', '--no-history', '--nohooks']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Program Files\Microsoft Visual Studio\2022\Community\ungoogled-chromium-windows\build.py", line 257, in <module>
    main()
  File "C:\Program Files\Microsoft Visual Studio\2022\Community\ungoogled-chromium-windows\build.py", line 179, in main
    subprocess.run([sys.executable, str(Path('ungoogled-chromium', 'utils', 'clone.py')), '-o', 'build\src', '-p', 'win32' if args.x86 else 'win64'], check=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\python3.exe', 'ungoogled-chromium\\utils\\clone.py', '-o', 'build\\src', '-p', 'win64']' returned non-zero exit status 1.

**Comment by TenmaSennpai** [comment]
IMPORTANT: Please setup only what is referenced below. Do NOT setup other Chromium compilation tools like depot_tools, since we have a custom build process which avoids using Google's pre-built binaries.
