### ISSUE TITLE
httplib2 not found even i installed it with every method available.

### ISSUE THREAD

**Issue by Jazzykhan** [ungoogled-software/ungoogled-chromium-windows#349]
(myenv310) PS C:\ungoogled-chromium-windows> python .\build.py
INFO: Downloading required files...
INFO: Downloading "bison-bin" to "bison-2.4.1-bin.zip" ...
INFO: C:\ungoogled-chromium-windows\build\download_cache\bison-2.4.1-bin.zip already exists. Skipping download.
INFO: Downloading "bison-dep" to "bison-2.4.1-dep.zip" ...
INFO: C:\ungoogled-chromium-windows\build\download_cache\bison-2.4.1-dep.zip already exists. Skipping download.
INFO: Downloading "bison-lib" to "bison-2.4.1-lib.zip" ...
INFO: C:\ungoogled-chromium-windows\build\download_cache\bison-2.4.1-lib.zip already exists. Skipping download.
INFO: Downloading "esbuild" to "esbuild-windows-64-0.14.13.tgz" ...
INFO: C:\ungoogled-chromium-windows\build\download_cache\esbuild-windows-64-0.14.13.tgz already exists. Skipping download.
INFO: Downloading "git" to "PortableGit-2.30.1-64-bit.7z.exe" ...
INFO: C:\ungoogled-chromium-windows\build\download_cache\PortableGit-2.30.1-64-bit.7z.exe already exists. Skipping download.
INFO: Downloading "gperf" to "gperf-3.0.1-bin.zip" ...
INFO: C:\ungoogled-chromium-windows\build\download_cache\gperf-3.0.1-bin.zip already exists. Skipping download.
INFO: Downloading "llvm" to "LLVM-18.1.1-win64.exe" ...
INFO: C:\ungoogled-chromium-windows\build\download_cache\LLVM-18.1.1-win64.exe already exists. Skipping download.
INFO: Downloading "ninja" to "ninja-win-1.10.2.zip" ...
INFO: C:\ungoogled-chromium-windows\build\download_cache\ninja-win-1.10.2.zip already exists. Skipping download.
INFO: Downloading "nodejs" to "node-v16.17.0-win-x64.zip" ...
INFO: C:\ungoogled-chromium-windows\build\download_cache\node-v16.17.0-win-x64.zip already exists. Skipping download.
INFO: Downloading "rust-x64" to "rust-nightly-2024-04-12-x86_64-pc-windows-msvc.tar.gz" ...
INFO: C:\ungoogled-chromium-windows\build\download_cache\rust-nightly-2024-04-12-x86_64-pc-windows-msvc.tar.gz already exists. Skipping download.
INFO: Downloading "rust-x86" to "rust-nightly-2024-04-12-i686-pc-windows-msvc.tar.gz" ...
INFO: C:\ungoogled-chromium-windows\build\download_cache\rust-nightly-2024-04-12-i686-pc-windows-msvc.tar.gz already exists. Skipping download.
INFO: Verifying hashes for "bison-bin" ...
INFO: Verifying hashes for "bison-dep" ...
INFO: Verifying hashes for "bison-lib" ...
INFO: Verifying hashes for "esbuild" ...
INFO: Verifying hashes for "git" ...
INFO: Verifying hashes for "gperf" ...
INFO: Verifying hashes for "llvm" ...
INFO: Verifying hashes for "ninja" ...
INFO: Verifying hashes for "nodejs" ...
INFO: Verifying hashes for "rust-x64" ...
INFO: Verifying hashes for "rust-x86" ...
INFO: Setting up cloning environment
INFO: Cloning chromium source: 125.0.6422.60
remote: Total 0 (delta 0), reused 0 (delta 0)
HEAD is now at 3ac3319bff [M125] Maintain deprecation trial token metrics precedence
Removing out/
Removing third_party/rust-toolchain/
INFO: Cloning depot_tools
remote: Total 0 (delta 0), reused 0 (delta 0)
From https://chromium.googlesource.com/chromium/tools/depot_tools
 * branch            8402300bb716be3b23ab191004e532ec5d8a129d -> FETCH_HEAD
HEAD is now at 8402300 Update ValidateTarFile for GCS to support sysroot tarfile members
Removing git.bat
INFO: Cloning gn
HEAD is now at df98b866 [gn] Fix "link" in the //examples/simple_build/build/toolchain/BUILD.gn
INFO: Running gsync
Traceback (most recent call last):
  File "C:\ungoogled-chromium-windows\build\src\uc_staging\depot_tools\gclient.py", line 108, in <module>
    import gclient_scm
  File "C:\ungoogled-chromium-windows\build\src\uc_staging\depot_tools\gclient_scm.py", line 23, in <module>
    import gerrit_util
  File "C:\ungoogled-chromium-windows\build\src\uc_staging\depot_tools\gerrit_util.py", line 12, in <module>
    import httplib2
ModuleNotFoundError: No module named 'httplib2'
Traceback (most recent call last):
  File "C:\ungoogled-chromium-windows\ungoogled-chromium\utils\clone.py", line 298, in <module>
    main()
  File "C:\ungoogled-chromium-windows\ungoogled-chromium\utils\clone.py", line 294, in main
    clone(args)
  File "C:\ungoogled-chromium-windows\ungoogled-chromium\utils\clone.py", line 133, in clone
    run([str(gcpath), 'sync', '-f', '-D', '-R', '--no-history', '--nohooks'], check=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['build\\src\\uc_staging\\depot_tools\\gclient.bat', 'sync', '-f', '-D', '-R', '--no-history', '--nohooks']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\ungoogled-chromium-windows\build.py", line 293, in <module>
    main()
  File "C:\ungoogled-chromium-windows\build.py", line 179, in main
    subprocess.run([sys.executable, str(Path('ungoogled-chromium', 'utils', 'clone.py')), '-o', 'build\src', '-p', 'win32' if args.x86 else 'win64'], check=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\ungoogled-chromium-windows\\myenv310\\Scripts\\python.exe', 'ungoogled-chromium\\utils\\clone.py', '-o', 'build\\src', '-p', 'win64']' returned non-zero exit status 1.
(myenv310) PS C:\ungoogled-chromium-windows>

**Comment by Jazzykhan** [comment]
(myenv310) C:\ungoogled-chromium-windows>pip3 install httplib2
Requirement already satisfied: httplib2 in c:\ungoogled-chromium-windows\myenv310\lib\site-packages (0.22.0)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in c:\ungoogled-chromium-windows\myenv310\lib\site-packages (from httplib2) (3.1.2)
WARNING: You are using pip version 21.2.3; however, version 24.0 is available.
You should consider upgrading via the 'C:\ungoogled-chromium-windows\myenv310\Scripts\python.exe -m pip install --upgrade pip' command.

(myenv310) C:\ungoogled-chromium-windows>pip install httplib2
Requirement already satisfied: httplib2 in c:\ungoogled-chromium-windows\myenv310\lib\site-packages (0.22.0)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in c:\ungoogled-chromium-windows\myenv310\lib\site-packages (from httplib2) (3.1.2)
WARNING: You are using pip version 21.2.3; however, version 24.0 is available.
You should consider upgrading via the 'C:\ungoogled-chromium-windows\myenv310\Scripts\python.exe -m pip install --upgrade pip' command.

(myenv310) C:\ungoogled-chromium-windows>
