### ISSUE TITLE
After changing build.gn, the following error will appear during compilation. Has anyone encountered it? Can it be solved?

### ISSUE THREAD

**Issue by satanmp** [ungoogled-software/ungoogled-chromium-windows#378]
Even after recalling the changes, i get the same error.
Traceback (most recent call last):
File "C:\Projects\ungoogled\ungoogled-chromium-windows\build\src\build\toolchain\win\midl.py", line 459, in
sys.exit(main(sys.argv[1:]))
File "C:\Projects\ungoogled\ungoogled-chromium-windows\build\src\build\toolchain\win\midl.py", line 399, in main
overwrite_guids((os.path.join(outdir, file) if file else None
File "C:\Projects\ungoogled\ungoogled-chromium-windows\build\src\build\toolchain\win\midl.py", line 237, in overwrite_guids
overwrite_guids_tlb(tlb_file, dynamic_guids)
File "C:\Projects\ungoogled\ungoogled-chromium-windows\build\src\build\toolchain\win\midl.py", line 199, in overwrite_guids_tlb
contents, ntypes, type_off, guid_off, guid_len = get_tlb_contents(tlb_file)
File "C:\Projects\ungoogled\ungoogled-chromium-windows\build\src\build\toolchain\win\midl.py", line 104, in get_tlb_contents
assert contents[0:8] == b'MSFT\x02\x00\x01\x00'
AssertionError

**Comment by PF4Public** [comment]
What did you change?

**Comment by weiq119** [comment]
I encountered the same problem as you, but I have solved it. The updater_idl.tlb and updater_legacy_idl.tlb files in the path: src\third_party\win_build_output\midl\chrome\updater\app\server\win\x64 and the elevation_service_idl.tlb in the path: D:\ungoogled-chromium-windows\build\src\third_party\win_build_output\midl\chrome\elevation_service\x64 were set to empty files for unknown reasons (I don't understand the reason now), which caused the problem you mentioned. Just restore these files. At least I solved the problem by doing this
