### ISSUE TITLE
Visual Studio 2019 Community error

### ISSUE THREAD

**Issue by seanking2919** [ungoogled-software/ungoogled-chromium-windows#38]
Hi guys,

I set up my vs2019_install and WINDOWSSDKDIR environment variables. Despite this, I can't build without getting this error on Windows 10.

```
D:\ungoogled-chromium-windows\build\src>exit
D:\ungoogled-chromium-windows\build\src>call "D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat" >nul

D:\ungoogled-chromium-windows\build\src>set DEPOT_TOOLS_WIN_TOOLCHAIN=0

D:\ungoogled-chromium-windows\build\src>"out\Default\gn.exe" "gen" "out\Default" "--fail-on-unused-args"
Traceback (most recent call last):
  File "D:/ungoogled-chromium-windows/build/src/build/vs_toolchain.py", line 578, in <module>
    sys.exit(main())
  File "D:/ungoogled-chromium-windows/build/src/build/vs_toolchain.py", line 574, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "D:/ungoogled-chromium-windows/build/src/build/vs_toolchain.py", line 551, in GetToolchainDir
    runtime_dll_dirs = SetEnvironmentAndGetRuntimeDllDirs()
  File "D:/ungoogled-chromium-windows/build/src/build/vs_toolchain.py", line 94, in SetEnvironmentAndGetRuntimeDllDirs
    os.environ['GYP_MSVS_OVERRIDE_PATH'] = DetectVisualStudioPath()
  File "D:/ungoogled-chromium-windows/build/src/build/vs_toolchain.py", line 183, in DetectVisualStudioPath
    version_as_year = GetVisualStudioVersion()
  File "D:/ungoogled-chromium-windows/build/src/build/vs_toolchain.py", line 173, in GetVisualStudioVersion
    ' Supported versions are: %s.' % supported_versions_str)
Exception: No supported Visual Studio can be found. Supported versions are: 16.0 (2019), 15.0 (2017).
ERROR at //build/config/win/visual_studio_version.gni:27:7: Script returned non-zero exit code.
      exec_script("../../vs_toolchain.py", [ "get_toolchain_dir" ], "scope")
      ^----------
```

**Comment by seanking2919** [comment]
Never mind. I figured it out. When building Ungoogled Chromium, set an environment variable called GYP_MSVS_VERSION to whatever year/version of Microsoft Visual Studio you have. Gonna go ahead and see if I can add it to README.md
