### ISSUE TITLE
WindowsError: [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by playgithub** [ungoogled-software/ungoogled-chromium-windows#57]
git tag `85.0.4183.121-1.1`

log
```
> "C:\Users\aaa\Python27\python.EXE" "tools\gn\bootstrap\bootstrap.py" "-o" "out\Default\gn.exe" "--skip-generate-buildfiles"
Traceback (most recent call last):
  File "tools\gn\bootstrap\bootstrap.py", line 143, in <module>
    sys.exit(main(sys.argv[1:]))
  File "tools\gn\bootstrap\bootstrap.py", line 129, in main
    [ninja_binary, '-C', gn_build_dir, '-w', 'dupbuild=err', 'gn.exe'])
  File "C:\Users\aaa\Python27\lib\subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\aaa\Python27\lib\subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Users\aaa\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Users\aaa\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

**Comment by playgithub** [comment]
describe better in #62
