### ISSUE TITLE
There is a question. Why not all version

### ISSUE THREAD

**Issue by tasty0tomato** [ungoogled-software/ungoogled-chromium-windows#73]
Like 87.0.4280.88 or 86.0.4240.198.

**Comment by tasty0tomato** [comment]
I tried to follow Developer info and changed ungoogled-chromium to 87.0.4280.88 and when I run
`./ungoogled-chromium/utils/downloads.py unpack -i ungoogled-chromium/downloads.ini -c build/download_cache build/src`
There seemed to have a error
```/usr/bin/tar: chromium-87.0.4280.88/buildtools/third_party/libc++/trunk/test/std/input.output/filesystems/Inputs/static_test_env/symlink_to_empty_file: Cannot create symlink to ‘empty_file’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/buildtools/third_party/libc++/trunk/test/std/input.output/filesystems/Inputs/static_test_env/symlink_to_dir: Cannot create symlink to ‘dir1’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/buildtools/third_party/libc++/trunk/test/std/input.output/filesystems/Inputs/static_test_env/bad_symlink: Cannot create symlink to ‘dne’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/chromeos/components/camera_app_ui/resources/cca: Cannot create symlink to ‘utils/cca.py’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/third_party/libdrm/src/intel/tests/gen7-2d-copy.batch.sh: Cannot create symlink to ‘test-batch.sh’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/third_party/libdrm/src/intel/tests/gen4-3d.batch.sh: Cannot create symlink to ‘test-batch.sh’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/third_party/libdrm/src/intel/tests/gen5-3d.batch.sh: Cannot create symlink to ‘test-batch.sh’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/third_party/webgl/src/specs/1.0: Cannot create symlink to ‘1.0.3’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/third_party/depot_tools/chrome_set_ver: Cannot create symlink to ‘cros’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/third_party/depot_tools/cros_sdk: Cannot create symlink to ‘cros’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/third_party/zxcvbn-cpp/LICENSE: Cannot create symlink to ‘LICENSE.txt’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/third_party/afl/src/README: Cannot create symlink to ‘docs/README’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/third_party/afl/src/QuickStartGuide.txt: Cannot create symlink to ‘docs/QuickStartGuide.txt’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/third_party/ukey2/src/NOTICE: Cannot create symlink to ‘LICENSE’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/third_party/llvm/clang/test/Driver/Inputs/basic_cross_linux_tree/usr/bin/x86_64-unknown-linux-gnu-ld: Cannot create symlink to ‘x86_64-unknown-linux-gnu-ld.gold’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/third_party/llvm/clang/test/Driver/Inputs/multilib_32bit_linux_tree/usr/bin/ld: Cannot create symlink to ‘i386-unknown-linux-gnu-ld’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/tools/luci-go/isolated: Cannot create symlink to ‘../../../.cipd/pkgs/7/_current/isolated’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/tools/luci-go/isolate: Cannot create symlink to ‘../../../.cipd/pkgs/6/_current/isolate’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/tools/luci-go/.versions/isolate.cipd_version: Cannot create symlink to ‘../../../../.cipd/pkgs/6/_current/.versions/isolate.cipd_version’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/tools/luci-go/.versions/swarming.cipd_version: Cannot create symlink to ‘../../../../.cipd/pkgs/8/_current/.versions/swarming.cipd_version’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/tools/luci-go/.versions/isolated.cipd_version: Cannot create symlink to ‘../../../../.cipd/pkgs/7/_current/.versions/isolated.cipd_version’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/tools/luci-go/swarming: Cannot create symlink to ‘../../../.cipd/pkgs/8/_current/swarming’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/third_party/checkstyle/checkstyle-all.jar: Cannot create symlink to ‘../../../.cipd/pkgs/2/_current/checkstyle-all.jar’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/third_party/catapult/third_party/gsutil/third_party/mock/docs/changelog.txt: Cannot create symlink to ‘../ChangeLog’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/third_party/devtools-frontend/src/node_modules/.bin/miller-rabin: Cannot create symlink to ‘../miller-rabin/bin/miller-rabin’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/third_party/devtools-frontend/src/node_modules/.bin/acorn: Cannot create symlink to ‘../acorn/bin/acorn’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/third_party/devtools-frontend/src/node_modules/.bin/sha.js: Cannot create symlink to ‘../sha.js/bin.js’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/third_party/perfetto/test/data: Cannot create symlink to ‘../buildtools/test_data’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/third_party/perfetto/ui/src/gen: Cannot create symlink to ‘../dist/gen’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/third_party/perfetto/infra/perfetto.dev/dist: Cannot create symlink to ‘../../out/perfetto.dev/site’: No such file or directory
/usr/bin/tar: chromium-87.0.4280.88/buildtools/third_party/libc++/trunk/test/std/pstl: Cannot create symlink to ‘../../../pstl/test/std’: No such file or directory
/usr/bin/tar: Exiting with failure status due to previous errors
ERROR: tar command returned 2
Traceback (most recent call last):
  File "./ungoogled-chromium/utils/downloads.py", line 437, in <module>
    main()
  File "./ungoogled-chromium/utils/downloads.py", line 433, in main
    args.callback(args)
  File "./ungoogled-chromium/utils/downloads.py", line 377, in _unpack_callback
    unpack_downloads(DownloadInfo(args.ini), args.cache, args.output, extractors)
  File "./ungoogled-chromium/utils/downloads.py", line 343, in unpack_downloads
    extractor_func(
  File "/c/Users/tasty/programming/ungoogled-chromium-windows/ungoogled-chromium/utils/_extraction.py", line 242, in extract_tar_file
    _extract_tar_with_tar(tar_bin, archive_path, output_dir, relative_to)
  File "/c/Users/tasty/programming/ungoogled-chromium-windows/ungoogled-chromium/utils/_extraction.py", line 129, in _extract_tar_with_tar
    raise ExtractionError()
_extraction.ExtractionError```

**Comment by Eloston** [comment]
I don't know either. It depends if someone is willing to update it.
