### ISSUE TITLE
Build version 90 fails when patching

### ISSUE THREAD

**Issue by berfito** [ungoogled-software/ungoogled-chromium-windows#85]
Hello everyone!

I have tried several times to compile version 90 (both 90.0.4430.93 and the current 90.0.4430.212) but it always fails to apply the patches, showing me the following error:

patching file third_party/libxml/chromium/xml_reader.cc
INFO: * Applying windows-disable-reorder-fix-linking.patch (3/20)
patching file chrome/BUILD.gn
Hunk #2 FAILED at 99.
1 out of 2 hunks FAILED -- saving rejects to file chrome/BUILD.gn.rej
patching file chrome/test/chromedriver/BUILD.gn
patching file tools/perf/chrome_telemetry_build/BUILD.gn
Hunk #1 succeeded at 58 (offset 18 lines).
Traceback (most recent call last):
  File "C:\ungoogled-chromium-windows\build.py", line 220, in <module>
    main()
  File "C:\ungoogled-chromium-windows\build.py", line 182, in main
    patches.apply_patches(
  File "C:\ungoogled-chromium-windows\ungoogled-chromium\utils\patches.py", line 132, in apply_patches
    subprocess.run(cmd, check=True)
  File "C:\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\ungoogled-chromium-windows\\build\\src\\third_party\\git\\usr\\bin\\patch.exe', '-p1', '--ignore-whitespace', '-i', 'C:\\ungoogled-chromium-windows\\patches\\ungoogled-chromium\\windows\\windows-disable-reorder-fix-linking.patch', '-d', 'C:\\ungoogled-chromium-windows\\build\\src', '--no-backup-if-mismatch', '--forward']' returned non-zero exit status 1.

Has this same error occurred to someone else?

**Comment by berfito** [comment]
File chrome/BUILD.gn.rej :

--- chrome/BUILD.gn
+++ chrome/BUILD.gn
@@ -99,18 +75,10 @@ if (!is_android && !is_mac) {
     # Windows-only deps are OK because chrome_initial uses initialexe/chrome as
     # the output name for that platform.
     # See crbug.com/1146571.
-    if (is_win) {
-      public_deps += [ ":reorder_imports" ]
-      data_deps += [ ":reorder_imports" ]
-    }
   }
 
   executable("chrome_initial") {
-    if (is_win) {
-      output_name = "initialexe/chrome"
-    } else {
-      output_name = "chrome"
-    }
+    output_name = "chrome"
 
     # Because the sources list varies so significantly per-platform, generally
     # each platform lists its own files rather than relying on filtering or
