### ISSUE TITLE
[build] unable to build application

### ISSUE THREAD

**Issue by yakagami** [ungoogled-software/ungoogled-chromium-windows#89]
I get this error. I see others have gotten it yet I can't figure out how to fix. Maybe it should be added to the build instructions.

```
C:\Windows\System32\ungoogled-chromium-windows>py build.py
Python 3.9.5
Traceback (most recent call last):
  File "C:\Windows\System32\ungoogled-chromium-windows\build.py", line 220, in <module>
    main()
  File "C:\Windows\System32\ungoogled-chromium-windows\build.py", line 134, in main
    _test_python2(parser.error)
  File "C:\Windows\System32\ungoogled-chromium-windows\build.py", line 87, in _test_python2
    result.stdout.strip()))
AttributeError: 'NoneType' object has no attribute 'strip'

```
...and to show I have setup path variable for both:
```

C:\Windows\System32\ungoogled-chromium-windows>py -2
Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> ^Z


C:\Windows\System32\ungoogled-chromium-windows>py -3
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> ^Z
```
Any help in build would be appreciated.

**Comment by Eshanepicfighter** [comment]
I think the build.py command was only made for linux. All the current documentation on building suggests its on linux

**Comment by yakagami** [comment]
So what should I do to build for windows? just run `py package.py` or something else?

**Comment by tangalbert919** [comment]
You need to read the build instructions. Just from that error, you have not added Python 2 to `PATH`.
