### ISSUE TITLE
Need help for building. ExtractionError

### ISSUE THREAD

**Issue by Oganesson403** [ungoogled-software/ungoogled-chromium-windows#96]
Hi, I am new.
I was just following the instructions in ['Building'](https://github.com/ungoogled-software/ungoogled-chromium-windows#building).

I setup the build environment (visual studio, 7zip, python both versions and git), then cloned this repo using commands in https://github.com/ungoogled-software/ungoogled-chromium-windows#building-1.
Then setup MSYS2, and ran the 'pacman' and 'ln' command.
Now, in [Updating Patches](https://github.com/ungoogled-software/ungoogled-chromium-windows#updating-patches), when running unpack command, I get the following error, with several can not create symlink errors before this.

Am I missing something? Is there a need to install something related to tar?
Please help.

> ERROR: tar command returned 2
Traceback (most recent call last):
  File "/d/PortableGit/ungoogled-chromium-windows/./ungoogled-chromium/utils/downloads.py", line 437, in <module>
    main()
  File "/d/PortableGit/ungoogled-chromium-windows/./ungoogled-chromium/utils/downloads.py", line 433, in main
    args.callback(args)
  File "/d/PortableGit/ungoogled-chromium-windows/./ungoogled-chromium/utils/downloads.py", line 377, in _unpack_callback
    unpack_downloads(DownloadInfo(args.ini), args.cache, args.output, extractors)
  File "/d/PortableGit/ungoogled-chromium-windows/./ungoogled-chromium/utils/downloads.py", line 343, in unpack_downloads
    extractor_func(
  File "/d/PortableGit/ungoogled-chromium-windows/ungoogled-chromium/utils/_extraction.py", line 242, in extract_tar_file
    _extract_tar_with_tar(tar_bin, archive_path, output_dir, relative_to)
  File "/d/PortableGit/ungoogled-chromium-windows/ungoogled-chromium/utils/_extraction.py", line 129, in _extract_tar_with_tar
    raise ExtractionError()
_extraction.ExtractionError

**Comment by tangalbert919** [comment]
Try doing the unpack command in an Administrator Command Prompt instead of MSYS2.

**Comment by HMaker** [comment]
The building guide says to run on MSYS shell, but it fails with ExtractionError. So the guide should be updated to ask user to run the chromium src download and unpacking on an Administrator Prompt, it requires Python installed on Windows instead of MSYS.
